# question 1
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [2]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# question 2
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
arr1,arr2 = (list(map(int,input().split())) for i in range(2))
arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))

3 2 1 
5 6 4
[3 2 1 5 6 4]
[1 2 3 4 5 6]


# question 3
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(arr.shape,arr.size)

(3, 3) 9


# question 4
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
'''
    To convert a 1D array into a 2D array, we can use reshape(a, newshape, order='C').
    
    e.g arr = np.array([ [1,2,3,4,5,6,7,8,9] ]) 
        
        arr.shape O/P: (1, 9)
        
        arr.reshape(3,3)
        
        O/P: array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
    
'''

arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


# question 5
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [6]:
arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


# question 6
How to get unique items and counts of unique items?

In [7]:
list1 = [1,3,1,5,2,4]
list1 = list(set(list1))
print(list1)
print()
print(len(list1))

[1, 2, 3, 4, 5]

5
